name: CI

env:
  NODE_VERSION: "20.10.0"

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - .github/workflows/deploy-prd.yaml
      - .github/workflows/deploy-stg.yaml
      - .github/workflows/autorebase.yaml
      - .github/PULL_REQUEST_TEMPLATE.md
      - .github/ISSUE_TEMPLATE/**
      - .github/CODEOWNERS.md
      - "vscode/**"
      - "docs/**"
      - .editorconfig
      - .gitignore
      - .eslintrc.json
      - README.md
      - Makefile
      - mkdocs.yml
      - requirements.txt
      - Dockerfile.mkdocs
      - LICENSE

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci --silent

      - name: Check Build
        run: make build

      - name: Check Lint
        run: make lint

      - name: Check Tests
        run: make test
